### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by RoyBellingan** [PowerPalDev/provisioningServer#10]
- [ ] We need to create scenario in YML which we have with for example 3 differenct customer each having 10-15 devices of various types and then run it for some time and check that there are no error logs on backend.

- [ ] Also provisioning server UI needs to be done so that all those devices are added to provisioning server and that they receive proper config from the provisioning server. Also check logs and see if data is ok on the backend for the devices and that values make sense.

- [ ] Enable provisioning server to configure the ACLs and check that they work properly for those devices which we specified in YML. 

- [ ] Add error log for unexpected exceptions on simulator, provisioning server and backend. Those are just initial things which need to be done. 

- [ ] This is not fully testing the current codebases. After this is done then we will do some more tests involving more devices and different use cases.
